"""Mutation weak control and actual unimported namespace coverage; ClaudeOS only."""
from pathlib import Path
import os,platform,json,subprocess,hashlib
assert platform.node()=='claudeos' and os.getuid()==1000
root=Path.home()/'coding-standards-verification/bee-c10-2026-10-09';project=root/'project with spaces';c5=root.parent/'bee-c5-2026-10-08'
env=os.environ.copy();env.update(PATH=str(root/'venv/bin')+':'+str(c5/'bin')+':'+env['PATH'],XDG_CACHE_HOME=str(root/'cache/xdg'),XDG_CONFIG_HOME=str(root/'cache/config'),PIP_CONFIG_FILE='/dev/null',PIP_CACHE_DIR=str(root/'cache/pip'),PYTHONNOUSERSITE='1',CI='1',NO_COLOR='1')
rows=[]
def run(label,args,cwd=project,code=0,marker=None):
 r=subprocess.run(args,cwd=cwd,env=env,stdin=subprocess.DEVNULL,capture_output=True,text=True,timeout=1200);rows.append({'label':label,'argv':args,'cwd':str(cwd),'status':r.returncode,'expected':code,'diagnostic':marker,'stdout':r.stdout,'stderr':r.stderr});(root/'results/supplement.json').write_text(json.dumps(rows,indent=2)+'\n');print(label,r.returncode,flush=True);assert r.returncode==code and (marker is None or marker in r.stdout+r.stderr),(label,(r.stdout+r.stderr)[-6000:])
weak=root/'weak control';weak.mkdir();(weak/'src/schema').mkdir(parents=True);(weak/'tests').mkdir();(weak/'src/schema/example.py').write_bytes((project/'src/schema/example.py').read_bytes());(weak/'pyproject.toml').write_text((project/'pyproject.toml').read_text().replace('pytest_add_cli_args_test_selection = ["tests/"]','pytest_add_cli_args_test_selection = ["tests/test_weak.py"]'));(weak/'tests/test_weak.py').write_text('from schema.example import _is_numeric\ndef test_weak() -> None:\n    _is_numeric("1")\n')
run('weak-mutation-tool-completion',['mutmut','run','--max-children','1'],weak);run('weak-results',['mutmut','results','--all','true'],weak);run('weak-stats-export',['mutmut','export-cicd-stats'],weak);stats=json.loads((weak/'mutants/mutmut-cicd-stats.json').read_text());assert stats['survived']>0;records={str(p.relative_to(weak)):{'text':p.read_text(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in weak.rglob('*') if p.is_file() and p.suffix in ['.py','.toml','.json','.meta'] and '__pycache__' not in p.parts};(root/'results/weak-control.json').write_text(json.dumps({'stats':stats,'files':records,'scope':'Deliberately weak separate fixture. Tool0 with survivors is not a mutation quality pass/acceptance.'},indent=2)+'\n')
p=project/'src/unimported_namespace/coverage_probe.py';p.parent.mkdir();p.write_text('def uncovered(value: int) -> int:\n'+''.join(f'    if value == {i}:\n        return {i+1}\n' for i in range(60))+'    return -1\n')
run('unimported-namespace-coverage',['make','test-coverage'],code=2,marker='not reached');p.unlink();p.parent.rmdir();run('restored-reference-coverage',['make','test-coverage'])
