"""Final namespace coverage correction and current-source checks; ClaudeOS only."""
from pathlib import Path
import os,platform,json,subprocess,hashlib
assert platform.node()=='claudeos' and os.getuid()==1000
root=Path.home()/'coding-standards-verification/bee-c10-2026-10-09';project=root/'project with spaces';os.chdir(project);c5=root.parent/'bee-c5-2026-10-08';c4=root.parent/'bee-c4-2026-10-08'
env=os.environ.copy();env.update(PATH=str(root/'venv/bin')+':'+str(c5/'bin')+':'+env['PATH'],XDG_CACHE_HOME=str(root/'cache/xdg'),XDG_CONFIG_HOME=str(root/'cache/config'),PIP_CONFIG_FILE='/dev/null',PIP_CACHE_DIR=str(root/'cache/pip'),PYTHONNOUSERSITE='1',PRE_COMMIT_HOME=str(root/'cache/pre-commit'),CI='1',NO_COLOR='1')
rows=[]
def snap():return {p.relative_to(project).as_posix():hashlib.sha256(p.read_bytes()).hexdigest() for p in project.rglob('*') if p.is_file() and not any(x in p.parts for x in ['.git','.mypy_cache','.ruff_cache','.pytest_cache','mutants','__pycache__'])}
def run(label,args,code=0,marker=None,unchanged=True):
 before=snap();r=subprocess.run(args,env=env,stdin=subprocess.DEVNULL,capture_output=True,text=True,timeout=1200);after=snap();rows.append({'label':label,'argv':args,'status':r.returncode,'expected':code,'diagnostic':marker,'stdout':r.stdout,'stderr':r.stderr,'before':before,'after':after,'unchanged_required':unchanged});(root/'results/final-checks.json').write_text(json.dumps(rows,indent=2)+'\n');print(label,r.returncode,flush=True);assert r.returncode==code and (marker is None or marker in r.stdout+r.stderr) and (not unchanged or before==after),(label,(r.stdout+r.stderr)[-7000:]);return r
probe=Path('src/unimported_namespace/coverage_probe.py');assert probe.exists();run('namespace-source-included-floor',['make','test-coverage'],2,'not reached',False);probe.unlink();probe.parent.rmdir();run('restored-reference-coverage',['make','test-coverage'],unchanged=False)
# Additional actual named typing diagnostics, not arbitrary failure.
p=Path('src/untyped_probe.py');p.write_text('def untyped(value):\n    return value\n');run('intended-untyped-definition',['make','typecheck'],2,'[no-untyped-def]');p.unlink()
p=Path('src/assignment_probe.py');p.write_text('wrong: int = "not an int"\n');run('intended-typed-assignment',['make','typecheck'],2,'[assignment]');p.unlink()
for label,args in [('final-lint',['make','lint']),('final-format',['make','format-check']),('final-src-test-types',['make','typecheck']),('final-35-tests',['make','test']),('final-pip-check',['python','-m','pip','check']),('final-graph-audit-json',['pip-audit','--disable-pip','--no-deps','-r','requirements-reference.lock','-f','json']),('final-configured-mutation-report',['make','mutation-report']),('final-mutation-stats',['mutmut','export-cicd-stats'])]:run(label,args)
run('stage-final-current-sdk',['git','add','.'],unchanged=False);run('final-all-files-installed-hooks',[str(c4/'venv/bin/pre-commit'),'run','--all-files'])
record={'files':{p.relative_to(project).as_posix():{'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'text':p.read_text()} for p in project.rglob('*') if p.is_file() and not any(x in p.parts for x in ['.git','.mypy_cache','.ruff_cache','.pytest_cache','mutants','__pycache__']) and p.name!='.coverage'},'mutation_stats':json.loads(Path('mutants/mutmut-cicd-stats.json').read_text()),'native_scanner_sha256':hashlib.sha256((c5/'bin/gitleaks').read_bytes()).hexdigest(),'scope':'Current selected namespace/Pydantic/plugin/35tests/coverage/graph/optional3helper-mutants/hooks; not all model mutations/all platforms/full safety/auth/persistence.'};assert record['native_scanner_sha256']=='88f91962aa2f93ac6ab281d553b9e125f5197bbbce38f9f2437f7299c32e5509';(root/'results/final-candidate.json').write_text(json.dumps(record,indent=2)+'\n')
